project_id = "mungdetmcksxnuygyoyr"

[functions.qalaca-ai]
verify_jwt = false

[functions.qalaca-journalist]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.admin-bootstrap]
verify_jwt = false

[functions.admin-invite]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false
